In [1]:
Names = "Zafar Khan. Subrat Acharya, and Michael Dobroski"

In [2]:
# imports
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import matplotlib as mpl
import pandas as pd
import seaborn as sns
from sklearn import (datasets, neighbors,
                     naive_bayes,
                     model_selection as skms,
                     linear_model, dummy,
                     metrics, preprocessing)
from sklearn import preprocessing
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder

In [6]:
car_train_plus_val_df = pd.read_csv("cartrain.csv")
car_test_df = pd.read_csv("cartest.csv")

#Useless Coloumns??
car_train_plus_val_df = car_train_plus_val_df.drop(['county'],axis=1)
car_train_plus_val_df = car_train_plus_val_df.drop(['url'],axis=1)
car_train_plus_val_df = car_train_plus_val_df.drop(['region_url'],axis=1)
#car_train_plus_val_df = car_train_plus_val_df.drop(['image_url'],axis=1)

#Fill in Missing Data
car_train_plus_val_df['condition'] = car_train_plus_val_df['condition'].replace({np.nan:"new"})


#Convert images

#Pipeline Steps
#scaler = skpre.StandardScaler()
            
#dummy = pd.get_dummies(car_train_plus_val_df['region']) #State, paint color, type, size, drive, Vin
                                                           #model, region, transmission, title_status, fuel
                                                           #cylinders, condition, manufacturer
display(car_train_plus_val_df)

,id,region,price,year,manufacturer,model,condition,cylinders,fuel,odometer,...,transmission,vin,drive,size,type,paint_color,image_url,state,lat,long
0,1,greensboro,10299,2012.0,acura,tl,new,NaN,gas,90186.0,...,automatic,19UUA8F22CA003926,NaN,NaN,other,blue,https://images.craigslist.org/01414_3LIXs9EO33...,nc,35.7636,-78.7443
1,2,greensboro,0,2011.0,bmw,335,new,6 cylinders,gas,115120.0,...,automatic,NaN,rwd,NaN,convertible,blue,https://images.craigslist.org/00S0S_1kTatLGLxB...,nc,NaN,NaN
2,4,greensboro,3995,2004.0,honda,element,new,NaN,gas,212526.0,...,automatic,5J6YH18314L006498,fwd,NaN,SUV,orange,https://images.craigslist.org/00E0E_eAUnhFF86M...,nc,35.7636,-78.7443
3,6,greensboro,12995,2015.0,kia,sportage,new,NaN,gas,85127.0,...,automatic,KNDPCCAC2F7761967,4wd,NaN,wagon,NaN,https://images.craigslist.org/00000_2qdQpZA2hK...,nc,35.7636,-78.7443
4,7,greensboro,10995,2014.0,chevrolet,traverse,new,NaN,gas,112383.0,...,automatic,1GNKRGKD2EJ157108,fwd,NaN,SUV,black,https://images.craigslist.org/00G0G_1DqITOauzg...,nc,35.7636,-78.7443
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313826,431692,san diego,10997,2017.0,toyota,corolla,new,NaN,gas,80702.0,...,automatic,2T1BURHE0HC906054,fwd,NaN,sedan,silver,https://images.craigslist.org/00F0F_lrIaAjAfNC...,ca,33.1950,-117.3780
313827,431693,chattanooga,12990,2013.0,toyota,rav4,new,NaN,gas,159161.0,...,automatic,JTMRFREV2DD004029,4wd,NaN,wagon,silver,https://images.craigslist.org/00505_hs4aSxP9bq...,tn,35.9233,-84.0607
313828,431694,san diego,0,2018.0,toyota,camry le sedan,excellent,NaN,gas,43221.0,...,automatic,4T1B11HK4JU059608,NaN,NaN,sedan,NaN,https://images.craigslist.org/00O0O_aK16j9lEbq...,ca,33.1605,-117.0980
313829,431695,philadelphia,5995,2007.0,infiniti,g,new,6 cylinders,gas,105753.0,...,automatic,JNKBV61F77M809853,NaN,NaN,sedan,custom,https://images.craigslist.org/00O0O_3Z5Z4PYw0N...,pa,40.0293,-74.9497
313830,431696,san diego,0,2012.0,chevrolet,camaro,new,NaN,gas,88925.0,...,automatic,2G1FK3DJ8C9183966,rwd,full-size,convertible,silver,https://images.craigslist.org/01212_512LLnOZdQ...,ca,33.7086,-117.8700

In [ ]:
pipe = pipeline.Pipeline(steps=[('scaler', scaler), 
                               ])